# docker-compose up

# docker-compose up -d

version: "3.8"

services:
  mongoDB:
    image: mongo
    container_name: Catalog.MongoDB.Compose
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: Contract.RabbitMQ.Compose
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  mongodbdata:
  rabbitmqdata:
